### ISSUE TITLE
Command for remnux upgrade

### ISSUE THREAD

**Issue by kryponix** [REMnux/docs#2]
The command to upgrade remnux appears as:
remnux upgrade OR sudo remnux upgrade
in different parts of the docs. I know the difference, but wonder whether that has implications on package installation. 
If it is intended to be this way, pls close this issue.

**Comment by lennyzeltser** [comment]
Thanks for spotting this inconsistency. I found one instance in the documentation where `sudo` didn't belong and removed it.
