### ISSUE TITLE
There is a problem with the documentation

### ISSUE THREAD

**Issue by summer-yin1** [REMnux/docs#3]
Hi guys, I found that there are two step5 titles in the GitHub doc document and official website: https://docs.remnux.org/install-distro/get-virtual-appliance, which seem to be duplicates?
![image](https://user-images.githubusercontent.com/68316873/94404658-eea3b280-01a1-11eb-83e4-d02e3ef18016.png)

**Comment by lennyzeltser** [comment]
Fixed! Thank you for noticing and opening the issue for this.
