### ISSUE TITLE
REMnux on high DPI displays

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/docs#8]
Has anyone had any success getting any flavor of Ubuntu 20.04 LTS scaling properly with high DPI displays, particularly in a VM? I need fractional scaling at ~175%, but all of the various options I've found offer 100% or 200% scaling, with nothing in between, at least on Ubuntu 20.04 LTS. I am able to get Linux Mint dialed in perfectly, but that won't work with REMnux, because Linux mint in a full fork of Ubuntu, with its own repositories.

The version of GNOME 3 included in the REMnux virtual appliance has a toggle for fractional scaling that does nothing.

I think this issue could be addressed in the new Ubuntu 22.04 LTS release. @lennyzeltser  If you need testing for this new Ubuntu release...

![I Volunteer as tribute GIF](https://user-images.githubusercontent.com/44679/166525909-3515d7a8-a7a5-4b13-af59-8937aed9cf1b.gif)

**Comment by seanthegeek** [comment]
I figured out that the fractional scaling options in GNOME 3 vary based on what resolution is currently selected, so you you don't see the desired scale option (or any scaling option), try selecting a different resolution.

**Comment by lennyzeltser** [comment]
Thanks for capturing the solution, @seanthegeek!
